package sesion1403.trabajos;

public enum Damage {
    TURBO_ROTO,EMBRAGUE_DESGASTADO,RUEDA_PINCHADA,INYECTOR_ROTO,FRENOS_DESGASTADOS,CHOQUE,LUNA_ROTA,SINIESTRO,BATERIA_ROTA,PERDIDA_DE_ACEITE,NO_DAÑOS
}
